# Generated by Django 5.1.2 on 2024-11-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
